USE MANGGOMDB;


DROP TABLE IF EXISTS MANAGER;
DROP TABLE IF EXISTS SALE_INFO;
DROP TABLE IF EXISTS TOTAL_SALES;
DROP TABLE IF EXISTS USER_INFO;
DROP TABLE IF EXISTS PRODUCT;


CREATE TABLE IF NOT EXISTS PRODUCT
(
	PRODUCT_CODE VARCHAR(5) PRIMARY KEY COMMENT '상품코드',
    PRODUCT_NAME VARCHAR(10) NOT NULL COMMENT '상품명',
    PRODUCT_COUNT INT NOT NULL COMMENT '상품개수',
    PRODUCT_PRICE INT NOT NULL COMMENT '상품가격'
) ENGINE=INNODB COMMENT '상품';

CREATE TABLE IF NOT EXISTS USER_INFO
(
	USER_NO INT AUTO_INCREMENT PRIMARY KEY COMMENT '사용자번호',
	USER_NAME VARCHAR(255) NOT NULL COMMENT '이름',
    USER_PHONE VARCHAR(13) NOT NULL COMMENT '전화번호',
    CUSTOMER_EMAIL VARCHAR(255) COMMENT '이메일',
	CUSTOMER_ADDR VARCHAR(255) NOT NULL COMMENT '주소'
) ENGINE=INNODB COMMENT '고객';

CREATE TABLE IF NOT EXISTS SALE_INFO
(
	SALE_NO INT AUTO_INCREMENT PRIMARY KEY COMMENT '판매번호',
    USER_NO INT COMMENT  '사용자번호',
    SALE_DATE DATE NOT NULL COMMENT '판매일자',
    PRODUCT_CODE VARCHAR(5) COMMENT '상품코드',
    SALE_COUNT INT NOT NULL COMMENT '판매개수',
    SALE_PRICE INT NOT NULL COMMENT '판매액',
    CONSTRAINT FK_USER_NO FOREIGN KEY (USER_NO) REFERENCES USER_INFO (USER_NO),
    CONSTRAINT FK_PRODUCT_CODE FOREIGN KEY (PRODUCT_CODE) REFERENCES PRODUCT (PRODUCT_CODE)
) ENGINE=INNODB COMMENT '구매정보';

CREATE TABLE IF NOT EXISTS MANAGER
(
	MANAGER_NO INT AUTO_INCREMENT PRIMARY KEY COMMENT '매니저번호',
	MANAGER_CODE VARCHAR(8) NOT NULL COMMENT '매니저코드',
    CONSTRAINT FK_MANAGER_NO FOREIGN KEY (MANAGER_NO) REFERENCES USER_INFO (USER_NO)
) ENGINE=INNODB COMMENT '매니저';

CREATE TABLE IF NOT EXISTS TOTAL_SALES
(
	PRODUCT_CODE VARCHAR(5) PRIMARY KEY COMMENT '상품코드',
    SALES_VOLUME INT NOT NULL COMMENT '판매량',
    REST_COUNT INT NOT NULL COMMENT '남은개수',
    SALES_AMOUNT INT NOT NULL COMMENT '총 판매액',
	CONSTRAINT FK_TOTAL_PRODUCT_CODE FOREIGN KEY (PRODUCT_CODE) REFERENCES PRODUCT (PRODUCT_CODE)
) ENGINE=INNODB COMMENT '매출현황';


INSERT INTO PRODUCT VALUES
(1, '티셔츠', 50, 30000),
(2, '키링', 50, 8000),
(3, '인형', 50, 20000),
(4, '담요', 50, 15000),
(5, '스티커', 50, 5000),
(6, '마우스', 50, 30000);

INSERT INTO USER_INFO VALUE
(0, '조형석', '010-4163-0989', NULL ,'서울시 강동구');


INSERT INTO MANAGER VALUE
(1, 'CHO123');